name: CI

on:
  push:
    branches:
    - master
  pull_request:
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  MINVERBUILDMETADATA: build.${{ github.run_id }}.${{ github.run_attempt}}
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
      with:
        fetch-depth: 0
        filter: tree:0
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
    - name: Build and Test
      run: ./Build.ps1
      shell: pwsh
    - name: Push to MyGet
      env:
        NUGET_URL: https://f.feedz.io/lucky-penny-software/mediatr/nuget/index.json
        NUGET_API_KEY: ${{ secrets.FEEDZIO_ACCESS_TOKEN }}
      run: ./Push.ps1
      shell: pwsh
    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: artifacts/**/*