name: Release

on:
  push:
    tags:
    - '*.*.*'
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  MINVERBUILDMETADATA: build.${{ github.run_id }}.${{ github.run_attempt}}
jobs:
  build:
    strategy:
      matrix: 
        os: [windows-2025]
      fail-fast: false
    runs-on: windows-2025
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: tree:0
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
    - name: Build and Test
      run: ./Build.ps1
      shell: pwsh
    - name: Push to MyGet
      env:
        NUGET_URL: https://f.feedz.io/lucky-penny-software/mediatr/nuget/index.json
        NUGET_API_KEY: ${{ secrets.FEEDZIO_ACCESS_TOKEN }}
      run: ./Push.ps1
      shell: pwsh
    - name: Push to NuGet
      env:
        NUGET_URL: https://api.nuget.org/v3/index.json
        NUGET_API_KEY: ${{ secrets.MEDIATR_NUGET_API_KEY }}
      run: ./Push.ps1
      shell: pwsh
    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: artifacts/**/*
